<?php

namespace Database\Seeders;

use App\Models\PlantMed;
use Illuminate\Support\Arr;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class PlantMedSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Symptoms list
        $symptoms = [
            'Acné',
            'Allergie',
            'Anémie',
            'Anorexie',
            'Anti-inflammatoire',
            'Antiseptique',
            'Anxiété',
            'Aphrodisiaque',
            'Arthrite',
            'Asthme',
            'Boulimie',
            'Bronchite',
            'Brûlures d\'estomac',
            'Brûlures',
            'Calculs biliaires',
            'Cellulite',
            'Cheveux',
            'Engelures',
            'Cholestérol',
            'Circulation sanguine',
            'Colite',
            'Côlon irritable',
            'Constipation',
            'Cystite (infection urinaire)',
            'Démangeaisons',
            'Dépression',
            'Dermatite',
            'Diabète',
            'Diarrhée',
            'Douleur menstruelle',
            'Elimination des toxines',
            'Fatigue',
            'Fertilité',
            'Fièvre',
            'Flatulence',
            'Foie gras',
            'Foie propre',
            'Froid',
            'glaucome',
            'Goutte',
            'Grippe',
            'Guérison',
            'Hémorroïdes',
            'Hyperhidrose',
            'Hypertension',
            'Hypotension',
            'Indigestion',
            'Infection de la gorge',
            'Cystite (infection urinaire)',
            'Insomnie',
            'Irritabilité',
            'Jambes fatiguées',
            'Mal de dents',
            'Maladies cardiovasculaires',
            'Maladie du foie',
            'Maladie rhumatismale',
            'Manque d\'appétit',
            'Mauvaise haleine',
            'Maux d\'estomac',
            'Maux de tête',
            'Ménoapuse',
            'Migraine',
            'Nausées',
            'Nerfs',
            'Névralgie',
            'Pancréatite',
            'Parasites intestinaux',
            'Peau sèche',
            'perdre du poids',
            'Pharyngite',
            'Plaies dans la bouche',
            'amnésie',
            'Problèmes digestifs',
            'Prostate',
            'Psoriasis',
            'Purifier les reins',
            'Rétention d\'eau',
            'Salpingite',
            'Sinusite',
            'Spasmes intestinaux',
            'Piqûres d\'insectes',
            'Stress',
            'Tache de peau',
            'Tachycardie',
            'Tendinite',
            'Toux',
            'Ulcère de l\'estomac',
            'Urétite',
            'Varices',
            'Vertiges',
            'Viellissement',
            'Vomissements',
        ];

        // Plant medicines list
        $plant_meds = [
            "Absinthe",
            "Achillée",
            "Actée à grappe",
            "Agave",
            "Agripaume",
            "Aigremoine",
            "Ail",
            "Aloe vera",
            "Amandier",
            "Amarante",
            "Aneth",
            "Angélique",
            "Arbre à thé",
            "Argousier",
            "Armoise commune",
            "Arnica",
            "Artichaut",
            "Ashwagandha",
            "Aubépine monogyne",
            "Açaï",
            "Badianer de Chine",
            "Bardane",
            "Basilic",
            "Bistorte",
            "Bleuet",
            "Boldo",
            "Bougainvillea",
            "Bouleau",
            "Bourrache",
            "Brocoli",
            "Buchu",
            "Cacao",
            "Callune",
            "Camomille",
            "Cannabis",
            "Cannelier",
            "Cardamome",
            "Caroubier",
            "Centaurée rude",
            "Centella asiatica",
            "Chardon Marie",
            "Chicorée",
            "Chélidoine",
            "Citronelle",
            "Citronnier",
            "Coffea",
            "Consoude",
            "Coquelicot",
            "Coriandre",
            "Cresson",
            "Cumin",
            "Cumin des près",
            "Curcuma",
            "Céleri",
            "Damiana",
            "Droséra",
            "Estragon",
            "Eucalyptus",
            "Fenouil",
            "Fleur d'oranger ",
            "Fumeterre",
            "Gattillier",
            "Gentiana",
            "Gimgembre",
            "Ginkgo",
            "Ginseng",
            "Giroflier",
            "Grand Plantain",
            "Grande Aunée",
            "Groseillier à maquereau",
            "Guimauve",
            "Hamamélis",
            "Helichrysum",
            "Hibiscus",
            "Houblon",
            "Ibéris amer",
            "Jasmin",
            "Laurier",
            "Lavande",
            "Lichen d'Islande",
            "Lin",
            "Luzerne",
            "Malva",
            "Manioc",
            "Marcela",
            "Marjolaine",
            "Marronnier",
            "Marrube blanc",
            "Maté",
            "Menthe",
            "Menthe poivrée",
            "Millepertuis perforé",
            "Molène thapsus",
            "Maringa",
            "Myrtille",
            "Mélisse",
            "Noyer",
            "Olivier",
            "Onagre",
            "Origan",
            "Orthosiphon",
            "Ortie",
            "Oseille",
            "Passiflora",
            "Pensée",
            "Persil",
            "Pin",
            "Pissenlit",
            "Poivron",
            "Pourpier",
            "Prunellier",
            "Prêle des champs",
            "Pâquerette",
            "Pérille",
            "Romarin",
            "Rooibos",
            "Rosier des chiens",
            "Rosier rouillé",
            "Ruda",
            "Réglisse",
            "Safran",
            "Salsepareille",
            "Sarriette vivace",
            "Sauge",
            "Saule blanc",
            "Serpolet",
            "Shatavari",
            "Soies de maïs",
            "Souci",
            "Stevia",
            "Sureau",
            "Séné",
            "Thym",
            "Thé",
            "Tilia",
            "Trèfle des prés",
            "Tussilage",
            "Ulmarie",
            "Valérianne",
            "Vanilla",
            "Verge d'or",
            "Verveine",
            "Verveine citronée",
            "Vigne",
            "Échinacée",
            "Épazote",
            "Épine-vinette",
            "Fenugrec",
            "Framboisier",
            "Gingembre",
            "Moringa"
        ];

        // http image
        // $image_url = 'https://everbloom.rn-admin.site/storage/b1XU1Z2Acr87FV6Qhh5sirw9E4v3Qqji5SxYXl6X.jpg';

        // $images = [
        //     'https://everbloom.rn-admin.site/storage/VmrTiMPE50AVJBgZ5Vfxg2Zz9DoMZ3fOuVPBNfyh.jpg',
        //     'https://everbloom.rn-admin.site/storage/yvxkg5WrOv1FIRczJdWfKoOwxwfH3nB9qkwzyRaN.jpg',
        //     'https://everbloom.rn-admin.site/storage/pW1qWPMBl4zPUASMeKCw5iocCuw8XXO22ui2GIqz.jpg'
        // ];

        // $sources = [
        //     'https://www.healthline.com/nutrition/10-proven-benefits-of-spirulina',
        //     'https://www.healthline.com/nutrition/10-proven-benefits-of-spirulina',
        //     'https://www.healthline.com/nutrition/10-proven-benefits-of-spirulina',
        // ];

        foreach ($plant_meds as $plant_med) {
            $random_symptoms = Arr::random($symptoms, 5);

            PlantMed::create([
                'name' => $plant_med,
                'nscient' => $plant_med . 'nscient',
                'famille' => $plant_med . 'famille',
                'genre' => $plant_med . 'genre',
                'description' => $plant_med . 'description',
                'habitat' => $plant_med . 'habitat',
                'propriete' => $plant_med . 'propriete',
                'usageInterne' => $plant_med . 'usageInterne',
                'usageExterne' => $plant_med . 'usageExterne',
                'precaution' => $plant_med . 'precaution',
                // 'image' => $image_url,
                // 'images' => json_encode($images),
                // 'symptoms' => json_encode($random_symptoms),
                // 'sources' => json_encode($sources),
                'is_featured' => (bool)rand(0, 1),
                'is_best_seller' => (bool)rand(0, 1),
                'is_active' => true,
                'is_available' => true,
            ]);
        }
    }
}
